### ISSUE TITLE
Wrong HTML after update

### ISSUE THREAD

**Issue by Allmedialab** [JayeshLab/bootstrap-5-sass-gulp-4-boilerplate#1]
Hi JayeshLab,

There are 2 issues with the template! The Bootstrap Carousel doesn't function and the mobile menu doesn't collapse. The reason is that the HTML changed from both with the latest update from Bootstrap 5. Just copy the code from the Get Bootstrap website and you be OK.

Thanks for the wonderful boilerplate! 
Warm Regards,

David

**Comment by JayeshLab** [comment]
Hi David,
Thanks for raising the issue. I have upgraded to latest Bootstrap v5.0.0-beta1 and updated the HTML. That will resolve issue.
Jayesh
