### ISSUE TITLE
Wrong build after latest update

### ISSUE THREAD

**Issue by Allmedialab** [JayeshLab/bootstrap-5-sass-gulp-4-boilerplate#4]
Hi JayeshLab,

After the latest update when applying gulp the build shows errors in the console and stuff is missing in the dist folder!
Hope you can fix it soon, tested it on Mac and Windows. Adding new dependencies doesn't work as well. They only appear in the Node_Modules. app.js is also doing nothing!

Regards & Thanks,

David

**Comment by JayeshLab** [comment]
Fixed it, issue is with path of node_modules new popper.js path in gulp.js
